// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgficMjoitMEturJcwoMuwyx8srQLlDsY',
    appId: '1:394636108040:web:fc0928f5994b441cfa0cbd',
    messagingSenderId: '394636108040',
    projectId: 'flutterauthen-8e1fc',
    authDomain: 'flutterauthen-8e1fc.firebaseapp.com',
    storageBucket: 'flutterauthen-8e1fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARR5xZZTK2kFzSTvlTGJPwwSdzcro-rYg',
    appId: '1:394636108040:android:f9bb3b8fa9f827c0fa0cbd',
    messagingSenderId: '394636108040',
    projectId: 'flutterauthen-8e1fc',
    storageBucket: 'flutterauthen-8e1fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1lEipBEamHc9V55e7PDntbuQiuQJ5AM',
    appId: '1:394636108040:ios:9dd5ece4029f12e3fa0cbd',
    messagingSenderId: '394636108040',
    projectId: 'flutterauthen-8e1fc',
    storageBucket: 'flutterauthen-8e1fc.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1lEipBEamHc9V55e7PDntbuQiuQJ5AM',
    appId: '1:394636108040:ios:d4881091364cd725fa0cbd',
    messagingSenderId: '394636108040',
    projectId: 'flutterauthen-8e1fc',
    storageBucket: 'flutterauthen-8e1fc.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
